version: '3.8'

services:
    backend:
        build: 
            context: ./backend
        ports:
            - '8086:8086'
        container_name: snmp-backend

    frontend:
        build: 
            context: ./frontend/client
            args:
                VITE_API_BASE_URL: 'http://localhost:8086/api'
        ports:
            - '3000:80'
        container_name: snmp-frontend
